version: '3.4'

services:
  gateway:
    build: gateway/
    depends_on:
      - 'spotify'
    ports:
      - '8000:8000'

  spotify:
    build: spotify/
    depends_on:
      - 'spotifyCache'
    ports:
      - '1000:1000'

  spotify-graph:
    build: spotify-graph/
    ports:
      - '1337:1337'

  twitter:
    build: twitter/
    ports:
      - '2000:2000'

  youtube:
    build: youtube/
    depends_on:
      - 'youtubeCache'
    ports:
      - '3000:3000'

  spotifyCache:
    image: redis:latest

  youtubeCache:
    image: redis:latest
