version: '3.4'

services:
  # client:
  #   build: client/
  #   depends_on:
  #     - 'gateway'
  #   ports:
  #     - '6000:6000'

  gateway:
    build: gateway/
    volumes:
      - ./gateway/:/gateway/
    depends_on:
      - 'spotify-graph'
      - 'twitter-graph'
      - 'youtube-graph'
    ports:
      - '8000:8000'

  spotify:
    build: spotify/
    volumes:
      - ./spotify/:/spotify/
    depends_on:
      - 'spotifyCache'
    ports:
      - '1000:1000'

  spotify-graph:
    build: spotify-graph/
    volumes:
      - ./spotify-graph/:/spotify-graph/
    ports:
      - '1337:1337'

  twitter:
    build: twitter/
    volumes:
      - ./twitter/:/twitter/
    depends_on:
      - 'twitterCache'
    ports:
      - '2000:2000'

  twitter-graph:
    build: twitter-graph/
    volumes:
      - ./twitter-graph/:/twitter-graph/
    depends_on:
      - 'twitterCache'
    ports:
      - '2337:2337'

  youtube:
    build: youtube/
    volumes:
      - ./youtube/:/youtube/
    depends_on:
      - 'youtubeCache'
    ports:
      - '3000:3000'

  youtube-graph:
    build: youtube-graph/
    volumes:
      - ./youtube-graph/:/youtube-graph/
    ports:
      - '3337:3337'

  spotifyCache:
    image: redis:latest

  twitterCache:
    image: redis:latest

  youtubeCache:
    image: redis:latest