version: '3.4'

services:
  etl:
    build: etl/
    depends_on:
      - 'gateway'
      - 'redisGraph'
    ports:
      - '8000:8000'

  gateway:
    build: gateway/
    depends_on:
      - 'spotify-graph'
      - 'twitter-graph'
      - 'youtube-graph'
    ports:
      - '4000:4000'

  spotify:
    build: spotify/
    depends_on:
      - 'spotifyCache'
    ports:
      - '1000:1000'

  spotify-graph:
    build: spotify-graph/
    ports:
      - '1337:1337'

  twitter:
    build: twitter/
    ports:
      - '2000:2000'

  twitter-graph:
    build: twitter-graph/
    ports:
      - '2337:2337'

  youtube:
    build: youtube/
    depends_on:
      - 'youtubeCache'
    ports:
      - '3000:3000'

  youtube-graph:
    build: youtube-graph/
    ports:
      - '3337:3337'

  spotifyCache:
    image: redis:latest

  youtubeCache:
    image: redis:latest

  redisGraph:
    image: redislabs/redisgraph:latest