version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@1.7.0
jobs:
  test-build:
    docker:
      - image: 'jackywu1/twitter:latest'
    steps:
      - checkout
      - node/install-packages
      - run: cd twitter && npm install && npm test

workflows:
  test-script:
    jobs:
      - test-build
