version: 2.1

orbs:
  node: circleci/node@latest
  docker: circleci/docker@latest
jobs:
  test-build:
    docker:
      - image: 'jackywu1/twitter:latest'
    steps:
      - checkout
      - node/install-packages
      - run: cd twitter && npm install && npm test

workflows:
  test-script:
    jobs:
      - test-build
  build-image:
    jobs:
      - docker/publish:
        - image: 'jackywu1/twitter:latest'